version: "3"
services:
  web:
    image: mpuma17/practica2detector:parte1 
    deploy: 
      replicas: 5 
      restart_policy: 
        condition: on-failure
    ports:
      - "4000:80"
    volumes:
      - shared-data:/app #Parte 2:Deteccion de anomalias
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis   
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet 
  redis:
    image: redislabs/redistimeseries:latest
    ports:
      - "6379:6379" 
    hostname: redis  
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  grafana: 
    image: grafana/grafana 
    ports: 
      - 3000:3000 
    volumes: 
      - grafana_data:/var/lib/grafana 
    depends_on: 
      - redis 
    networks:
      - webnet
    environment: 
      GF_INSTALL_PLUGINS: redis-datasource 
volumes: 
  grafana_data:
  shared-data: #Parte 2:Deteccion de anomalias
networks:
  webnet:
